# Generated by Django 5.2rc1 on 2025-04-09 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claimrequest",
            name="admin_notes",
        ),
        migrations.RemoveField(
            model_name="claimrequest",
            name="proof_document",
        ),
    ]
