# Generated by Django 5.2rc1 on 2025-04-11 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_claimrequest_admin_notes_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="claimrequest",
            name="business",
        ),
        migrations.RemoveField(
            model_name="claimrequest",
            name="user",
        ),
        migrations.DeleteModel(
            name="BusinessListing",
        ),
        migrations.DeleteModel(
            name="ClaimRequest",
        ),
    ]
