# Generated by Django 5.2rc1 on 2025-04-11 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0002_remove_user_date_of_birth_user_user_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="category",
            field=models.CharField(
                choices=[
                    ("accommodation", "Accommodation"),
                    ("food_drinks", "Food & Drinks"),
                    ("activities", "Activities"),
                    ("shopping", "Shopping"),
                    ("health", "Health"),
                    ("entertainment", "Entertainment"),
                    ("services", "Services"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="city",
            field=models.CharField(
                blank=True, default="Kampala", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="district",
            field=models.CharField(
                blank=True, default="Kampala", max_length=100, null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="price_range",
            field=models.CharField(
                blank=True,
                choices=[
                    ("$", "Budget"),
                    ("$$", "Moderate"),
                    ("$$$", "Expensive"),
                    ("$$$$", "Luxury"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="rating",
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=3),
        ),
        migrations.AddField(
            model_name="user",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
