# Generated by Django 5.2rc1 on 2025-04-11 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0003_profile_category_profile_city_profile_district_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="category",
        ),
        migrations.AddField(
            model_name="user",
            name="business_category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("accommodation", "Accommodation"),
                    ("food_drinks", "Food & Drinks"),
                    ("activities", "Activities"),
                    ("shopping", "Shopping"),
                    ("health", "Health"),
                    ("entertainment", "Entertainment"),
                    ("services", "Services"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
