# Generated by Django 5.2rc1 on 2025-04-16 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0005_profile_tags_bookmark"),
    ]

    operations = [
        migrations.RenameField(
            model_name="profile",
            old_name="linkedin",
            new_name="facebook",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="city",
        ),
        migrations.AddField(
            model_name="profile",
            name="county",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="parish",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="sub_county",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="profile",
            name="village",
            field=models.CharField(blank=True, default=" ", max_length=100, null=True),
        ),
    ]
