# Generated by Django 5.2rc1 on 2025-06-02 16:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cities", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, max_length=220, unique=True)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("natural", "Natural Attraction"),
                            ("historical", "Historical Site"),
                            ("cultural", "Cultural Venue"),
                            ("entertainment", "Entertainment"),
                            ("shopping", "Shopping"),
                            ("food", "Food & Dining"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("website", models.URLField(blank=True, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="attractions/images/"
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "city",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="city_attractions",
                        to="cities.city",
                    ),
                ),
            ],
            options={
                "verbose_name": "Attraction",
                "verbose_name_plural": "Attractions",
                "ordering": ["name"],
            },
        ),
    ]
